version: "3.8"

x-restart-policy: &default_restart_policy
  restart: ${DEFAULT_RESTART_POLICY}

services:
  proxy:
    image: traefik:2.10
    <<: *default_restart_policy
    hostname: "traefik"
    labels:
      - traefik.enable=true
      - traefik.docker.network=hubnet
      - traefik.http.routers.traefik.rule=Host(`${TRAEFIK_ADDRESS}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.entrypoints=web

    networks:
      - hubnet
    ports:
      - 80:80
      - 443:443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./proxy/proxy-config.yml:/etc/traefik/traefik.yml:ro

  mongo:
    build:
      context: ./mongo
    <<: *default_restart_policy
    env_file:
      - mongo/mongo.env
    hostname: "mongo"
    networks:
      - hubintranet
      - hubnet
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo-data:/data/db

  keycloak:
    build:
      context: ./keycloak
      args:
        - KC_VER=20.0
    <<: *default_restart_policy
    command: start-dev --import-realm
    container_name: keycloak
    depends_on:
      - keycloak-db
    env_file:
      - keycloak/keycloak.env
    hostname: "keycloak"
    labels:
      - traefik.enable=true
      - traefik.docker.network=hubnet
      - traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_ADDRESS}`)
      - traefik.http.routers.keycloak.entrypoints=web
      - traefik.http.services.keyloak.loadbalancer.server.port=8080
      - traefik.http.services.keyloak.loadbalancer.server.scheme=http
    networks:
      - keycloaknet
      - hubintranet
      - hubnet

    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./keycloak/werkstatthub-realm.json:/opt/keycloak/data/import/wh.json:ro
    healthcheck:
      test: curl --head -fsS http://localhost:8080/health/ready || exit 1
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 30s

  keycloak-config:
      image: quay.io/keycloak/keycloak:20.0
      depends_on:
          keycloak:
              condition: service_healthy
      entrypoint: ["sh","-c","chmod +x /init.sh && ./init.sh"]
      env_file:
        - keycloak/keycloak.env
      networks:
        - hubintranet
      user: root
      volumes:
        - ./keycloak/keycloak-config.sh:/init.sh

  keycloak-db:
    image: postgres:15-alpine
    <<: *default_restart_policy
    container_name: keycloak-db
    env_file:
      - postgres/postgres.env
    hostname: "keycloak-db"
    networks:
      - keycloaknet
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    build:
      context: ./minio
      args:
          - MINIO_VER=RELEASE.2023-05-27T05-56-19Z
    <<: *default_restart_policy
    command: server /data --console-address ":9090"
    hostname: "minio"
    depends_on:
      keycloak-config:
        condition: service_completed_successfully
    env_file:
      - minio/minio.env
    labels:
      - traefik.enable=true
      - traefik.docker.network=hubnet
      - traefik.http.routers.minio.rule=Host(`${MINIO_ADDRESS}`)
      - traefik.http.routers.minio.entrypoints=web
      - traefik.http.services.minio.loadbalancer.server.port=9090
      - traefik.http.services.minio.loadbalancer.server.scheme=http
    networks:
      - hubintranet
      - hubnet
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - minio-data:/data
    healthcheck:
      test: curl -fs http://localhost:9000/minio/health/live || exit 1
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 30s

  minio-config:
      image: minio/mc
      depends_on:
          minio:
              condition: service_healthy
      entrypoint: ["sh","-c","chmod +x /minio-config.sh && ./minio-config.sh"]
      environment:
          - S3_ROOT_USER=${S3_ROOT_USER}
          - S3_ROOT_PASSWORD=${S3_ROOT_PASSWORD}
      networks:
        - hubintranet
      volumes:
        - ./minio/minio-config.sh:/minio-config.sh

  api:
    build:
      context: ./api
    <<: *default_restart_policy
    # DEVELOPMENT: run with reload and mount api package code
    command: uvicorn --host 0.0.0.0 --reload api.main:app
    depends_on:
      - mongo
    env_file:
      - api/api.env
    hostname: "api"
    labels:
      - traefik.enable=true
      - traefik.docker.network=hubnet
      - traefik.http.routers.api.rule=Host(`${API_ADDRESS}`)
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.services.api.loadbalancer.server.port=8000
      - traefik.http.services.api.loadbalancer.server.scheme=http
    networks:
      - hubintranet
      - hubnet
    volumes:
      - ./api/api/:/home/api/api/

  docs:
    build:
      context: ./docs
    <<: *default_restart_policy
    labels:
      - traefik.enable=true
      - traefik.docker.network=hubnet
      - traefik.http.routers.docs.rule=Host(`${DOCS_ADDRESS}`)
      - traefik.http.routers.docs.entrypoints=web
      - traefik.http.services.docs.loadbalancer.server.port=80
      - traefik.http.services.docs.loadbalancer.server.scheme=http
    networks:
      - hubnet

networks:
  hubnet:
    name: hubnet
  hubintranet:
    internal: true
  keycloaknet:
    internal: true

volumes:
  mongo-data:
  postgres-data:
  minio-data:
