providers:
  docker:
    network: hubnet
    exposedByDefault: false
entrypoints:
  web:
    address: :80
  websecure:
    address: :443
    http:
      tls:
        options: default
  minio:
    address: :9000
tls:
  options:
    default:
      minVersion: VersionTLS12
log:
  level: ERROR
api: {}

