name: Build and publish docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/de/**"
jobs:
  build-docs:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      BUILD_WITH_PDF: 1

    steps:
      # Setup environment
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'

      # Build and publish docs
      - name: Install python dependencies
        run: pip install mkdocs-with-pdf

      - name: Set username and e-mail
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Fetch old changes if branch exists
        run: git fetch -f origin gh-pages:gh-pages || exit 0

      - name: Build and upload to gh-pages branch
        run: mkdocs gh-deploy --config-file ./docs/de/mkdocs.yml