name: Syntax Check API

on:
  pull_request:
    paths:
      - "api/api/**"
      - "api/tests/**"
jobs:
  syntaxcheck-api:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      # Setup environment
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'

      # Test Code Compliance
      - name: Install python dependencies
        run: pip install flake8

      - name: Run flake8
        run: flake8 ./api