name: Test Docker Stack

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      GH_SCHEME: http://
      GH_BASE_ADDRESS: werkstatthub.docker.localhost
      GH_FRONTEND_ADDRESS: ${{env.SCHEME}}${{env.BASE_ADDRESS}}
      GH_DOCS_ADDRESS: ${{env.SCHEME}}docs.${{env.BASE_ADDRESS}}
      GH_MINIO_ADDRESS: ${{env.SCHEME}}minio.${{env.BASE_ADDRESS}}
      GH_KEYCLOAK_ADDRESS: ${{env.SCHEME}}keycloak.${{env.BASE_ADDRESS}}
      GH_API_ADDRESS: ${{env.SCHEME}}api.${{env.BASE_ADDRESS}}
      GH_EDC_ADDRESS: ${{env.SCHEME}}edc.${{env.BASE_ADDRESS}}

    steps:
    # Setup environment
      - name: Checkout
        uses: actions/checkout@v1

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2

    # Tag Containers
      - name: Build and tag containers
        run: docker compose --env-file=dev.env build

    # Start Containers
      - name: Start containers and wait for healthy state
        run: docker compose --env-file=dev.env up -d --wait

    # Test documentation
      - name: Check if documentation is reachable
        run: |
          curl -fs -o /dev/null -w 'http_code:%{http_code}' \
          $GH_DOCS_ADDRESS \
          || exit 1

    # Test MongoDB
      - name: Check if MongoDB is reachable
        run: |
          curl -fs -o /dev/null -w 'http_code:%{http_code}' \
          http://localhost:27017 \
          || exit 1

    # Test Keycloak
      - name: Check if Keycloak is healthy
        run: |
          curl -fs \
          $GH_KEYLOAK_ADDRESS/health/live \
          || exit 1

    # Test MinIO
      - name: Check if MinIO is healthy
        run: |
          curl -fs \
          $GH_MINIO_ADDRESS/minio/health/live \
          || exit 1

    # Test EDC
      - name: Check if EDC is healthy
        run: |
            curl -fs \
            $GH_EDC_ADDRESS/api/health \
            || exit 1

    # Test API
      - name: Check if API is healthy
        run: |
          curl -fs \
          $GH_API_ADDRESS/v1/health/ping \
          || exit 1

      - name: Check for strict-transport-security header
        run: |
          curl -sIX GET $GH_API_ADDRESS/v1/health/ping \
            | grep -iq "strict-transport-security" \
            || exit 1

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest ./api

      - name: Run flake8
        run: flake8 ./api

    # Test Frontend
      - name: Check if Frontend is reachable
        run: |
          curl -fs \
          $GH_FRONTEND_ADDRESS \
          || exit 1

    # Clean up
      - name: Stop containers
        if: always()
        run: docker compose --env-file=dev.env down -v
