  name: Test Frontend

  on:
    pull_request:
      paths:
        - "frontend/**"
  jobs:
    test:
      timeout-minutes: 10
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - uses: dart-lang/setup-dart@v1
          with:
            sdk: 2.19.6
        - uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.7.12'
            channel: 'stable'

        - name: Disable dart/flutter analytics
          run: dart --disable-analytics && flutter config --no-analytics

        - name: Verify formatting
          run: cd ./frontend/app && dart format --output=none --set-exit-if-changed .

        - name: Install dependencies
          run: cd ./frontend/app && flutter pub get

        - name: Run build_runner
          run: cd ./frontend/app && flutter pub run build_runner build --delete-conflicting-outputs
          env:
            BACKEND_URL: http://127.0.0.1
            BASIC_AUTH_KEY: 
            KC_CLIENT: test
            KC_BASE_URL: http://127.0.0.1/realms/<REALM>/protocol/openid-connect/
            KC_REALM: test
            LOG_LEVEL: warning
            ROOT_DOMAIN: http://127.0.0.1
            REDIRECT_URI_MOBILE: http://127.0.0.1

        - name: Analyze project source
          run: cd ./frontend/app && dart analyze --fatal-infos

        - name: Run unit tests
          run: cd ./frontend/app && flutter test --no-pub --no-test-assets --reporter github
